[SignalGroups]

Sensors=IN_Fuel_temperature,C_I_Fuel_temperature,IN_Inlet_air_temperature,C_I_Fuel_filter_pressure,C_I_Rail_fuel_pressure,C_I_Eng_oil_temp,Pedal_1_pwm_dc_filt_value,Pedal_2_pwm_dc_filt_value,Pedal.Value,C_I_Cool_temp,CCV_Pump_speed,HPV_Current_feedback,C_I_Ext_air_temp,C_I_Egr_temp,Bpv_position.Value,Egr_position.Value,Vgt_position.Value,Turbo_speed

Fuelling=Actual_fuel_value,CCV_Pump_speed,C_I_Cool_temp,C_I_turbo_out_pressure,C_I_doc_inlet_temperature,C_I_doc_out_temperature,System_state,IN_Fuel_temperature,C_I_Fuel_temperature,IN_Inlet_air_temperature,C_I_Fuel_filter_pressure,C_I_Rail_fuel_pressure,C_I_Eng_oil_temp


[Settings]
Sample_start_prctle = 0.45
Sample_end_prctle = 0.9
PValue_highlight_thres =0.05
DataDump=True